version: "3.7"
services:

  mariadb:
    image: "mariadb:latest"
    restart: 'always'
    volumes: 
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: raynetRootPassword
      MYSQL_DATABASE: datahub
      MYSQL_USER: raynetUser
      MYSQL_PASSWORD: raynetPassword
    ports:
      - 3307:3306

  web:
    image: raynetnightly.azurecr.io/raynet/rayventory/datahub:12.5.5081.73
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: always
    environment:
      - connectionStrings__System=Server=mariadb,3307;Database=datahub;User ID=root;Password=raynetRootPassword
      - connectionStrings__ReportDatabase=Server=mariadb,3307;Database=datahub;User ID=root;Password=raynetRootPassword
      - connectionStrings__Driver=mysql
      - TasksManagement__LogsDirectory=/app/raynet/datahub/task-logs
      - KotlinDirectoryPath=/app/raynet/datahub/kotlin
      - InitialTenantId={72ba6fc2-d5fa-49ee-8281-841e762aea05}
      - BASEURL=http://localhost:8080 
    volumes:
      - ./host-logs:/app/raynet/datahub/task-logs
    links:
      - mariadb
  agent:
    image: raynetnightly.azurecr.io/raynet/rayventory/datahub-agent:12.5.5081.73
    depends_on:
      - web
    restart: always
    environment:
      - DataHubUrl=http://web:80
      - TenantId={72ba6fc2-d5fa-49ee-8281-841e762aea05}
      - KotlinDirectoryPath=/app/raynet/datahub-agent/kotlin