apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-web'
spec:
  type: {{ .Values.web.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: 8080
      {{- if eq .Values.web.serviceType "NodePort" }}
      nodePort: 30080 # Optional: Specify a node port in the range 30000-32767
      {{- end }}
  selector:
    app: '{{ .Release.Name }}-web'
