apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-mariadb'
spec:
  type: {{ .Values.mariadb.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.mariadb.port }}
      targetPort: 3306
  selector:
    app: '{{ .Release.Name }}-mariadb'
